version: 2.1

############################################################################

executors:
  default-executor:
    working_directory: ~/scrapeData
    shell: /bin/bash
    docker:
      - image: circleci/node:11-browsers

  testcafe-executor:
    working_directory: ~/scrapeData
    shell: /bin/bash
    docker:
      - image: circleci/node:13.2.0-browsers

store-results: &store-results
  store_test_results:
    path: Data

store-artifacts: &store-artifacts
  store_artifacts:
    path: Data

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: ~/
    paths:
      - scrapeData

attach-workspace: &attach-workspace
  attach_workspace:
    at: ~/

# Save node_modules dependencies
save-dependencies-cache: &save-dependencies-cache
  save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

# Download node_modules dependencies
restore-dependencies-cache: &restore-dependencies-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      # fallback to using the cache from the same branch
      - v1-dependencies-{{ .Branch }}-
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

master-branch: &master-branch
  filters:
    branches:
      only:
        - master

workflows:
  version: 2

  ######################################

  # Feature/bug branch commit workflow
  commit-workflow:
    jobs:
      - npm-init:
          <<: *master-branch

      - google-tests:
          requires:
            - npm-init
          <<: *master-branch

      - Google-Map-approval:
          type: approval
          requires:
            - npm-init
          <<: *master-branch

      - Google-Map-Search:
          requires:
            - Google-Map-approval
          <<: *master-branch

jobs:
  npm-init:
    executor: testcafe-executor
    steps:
      - checkout

      - *restore-dependencies-cache

      # Install dependencies
      - run:
          name: Install npm modules
          command: npm install --no-fund --no-audit
          no_output_timeout: 15m

      - *save-dependencies-cache

      - *persist-workspace

  google-tests:
    executor: testcafe-executor
    parallelism: 2
    steps:
      - *attach-workspace

      - run:
          name: Run automation tests
          command: |
            TESTFILES=$(circleci tests glob "tests/GoogleTests" | circleci tests split --split-by=timings)
            node node_modules/testcafe/bin/testcafe.js "chrome -incognito" -e -u -c 8 ${TESTFILES} -T "AAAA" -S -s Data/screenshots -r xunit:Data/testcafe/result.xml

      - *store-artifacts
      - *store-results

  Google-Map-Search:
    executor: testcafe-executor
    steps:
      - *attach-workspace

      - run:
          name: Run Google maps automation tests
          command: node node_modules/testcafe/bin/testcafe.js "chrome -incognito" -c 8 tests/searchOnGoogleMaps.js -e -u

      - *store-artifacts
      - *store-results

